from pydantic import BaseModel, Field, field_validator
from datetime import date
from typing import Optional


class BookCreate(BaseModel):
    """
    Schema for creating a new book.
    
    Used in POST /books endpoint. Does not include id as it's generated by the database.
    """
    title: str = Field(..., min_length=1, max_length=200, description="Title of the book")
    author: str = Field(default="", max_length=100, description="Author of the book")
    start_date: date = Field(..., description="Date when reading started")
    
    @field_validator('title')
    @classmethod
    def validate_title(cls, v: str) -> str:
        """Validate that title is not empty or only whitespace."""
        if not v or not v.strip():
            raise ValueError('Title cannot be empty')
        return v.strip()
    
    @field_validator('author')
    @classmethod
    def validate_author(cls, v: str) -> str:
        """Strip whitespace from author."""
        return v.strip() if v else ""
    
    @field_validator('start_date')
    @classmethod
    def validate_start_date(cls, v: date) -> date:
        """Validate that start_date is not in the future."""
        if v > date.today():
            raise ValueError('Start date cannot be in the future')
        return v
    
    model_config = {
        "json_schema_extra": {
            "example": {
                "title": "The Pragmatic Programmer",
                "author": "Andrew Hunt",
                "start_date": "2024-01-15"
            }
        }
    }


class BookUpdate(BaseModel):
    """
    Schema for updating an existing book.
    
    Used in PUT /books/{id} endpoint. All fields are optional to allow partial updates.
    """
    title: Optional[str] = Field(None, min_length=1, max_length=200, description="New title of the book")
    author: Optional[str] = Field(None, max_length=100, description="New author of the book")
    start_date: Optional[date] = Field(None, description="Date when reading started")
    end_date: Optional[date] = Field(None, description="Date when reading finished")
    status: Optional[str] = Field(None, description="Reading status: 'reading' or 'finished'")
    
    @field_validator('title')
    @classmethod
    def validate_title(cls, v: Optional[str]) -> Optional[str]:
        """Validate that title is not empty or only whitespace if provided."""
        if v is not None:
            if not v.strip():
                raise ValueError('Title cannot be empty')
            return v.strip()
        return v
    
    @field_validator('author')
    @classmethod
    def validate_author(cls, v: Optional[str]) -> Optional[str]:
        """Strip whitespace from author if provided."""
        if v is not None:
            return v.strip() if v.strip() else None
        return v
    
    @field_validator('start_date')
    @classmethod
    def validate_start_date(cls, v: Optional[date]) -> Optional[date]:
        """Validate that start_date is not in the future if provided."""
        if v is not None and v > date.today():
            raise ValueError('Start date cannot be in the future')
        return v
    
    @field_validator('status')
    @classmethod
    def validate_status(cls, v: Optional[str]) -> Optional[str]:
        """Validate that status is either 'reading' or 'finished' if provided."""
        if v is not None and v not in ['reading', 'finished']:
            raise ValueError("Status must be 'reading' or 'finished'")
        return v
    
    model_config = {
        "json_schema_extra": {
            "example": {
                "title": "The Pragmatic Programmer (20th Anniversary)",
                "status": "finished",
                "end_date": "2024-03-20"
            }
        }
    }


class BookResponse(BaseModel):
    """
    Schema for book responses.
    
    Used in GET /books and GET /books/{id} endpoints. Represents complete book data
    including the database-generated ID.
    """
    id: int = Field(..., description="Unique identifier of the book")
    title: str = Field(..., description="Title of the book")
    author: str = Field(..., description="Author of the book")
    start_date: date = Field(..., description="Date when reading started")
    end_date: Optional[date] = Field(None, description="Date when reading finished (null if still reading)")
    status: str = Field(..., description="Reading status: 'reading' or 'finished'")
    
    model_config = {
        "from_attributes": True,
        "json_schema_extra": {
            "example": {
                "id": 1,
                "title": "The Pragmatic Programmer",
                "author": "Andrew Hunt",
                "start_date": "2024-01-15",
                "end_date": "2024-03-20",
                "status": "finished"
            }
        }
    }
