from pydantic import BaseModel, Field, field_validator
from datetime import date as DateType
from typing import Optional


class SessionCreate(BaseModel):
    """
    Schema for creating a new reading session.
    
    Used in POST /sessions endpoint. Does not include id as it's generated by the database.
    Users can log sessions for past dates (backfilling reading history).
    """
    book_id: int = Field(..., gt=0, description="ID of the book being read")
    date: DateType = Field(..., description="Date of the reading session (can be in the past)")
    minutes_read: int = Field(..., gt=0, description="Number of minutes read in this session")
    
    @field_validator('book_id')
    @classmethod
    def validate_book_id(cls, v: int) -> int:
        """Validate that book_id is positive."""
        if v <= 0:
            raise ValueError('Book ID must be positive')
        return v
    
    @field_validator('date')
    @classmethod
    def validate_date(cls, v: DateType) -> DateType:
        """
        Validate that session date is not in the future.
        
        Past dates are allowed - users can log old reading sessions.
        """
        if v > DateType.today():
            raise ValueError('Session date cannot be in the future')
        # Past dates are explicitly allowed for backfilling reading history
        return v
    
    @field_validator('minutes_read')
    @classmethod
    def validate_minutes(cls, v: int) -> int:
        """
        Validate that minutes read is positive and reasonable.
        
        Must be greater than 0 and not exceed 24 hours (1440 minutes).
        """
        if v <= 0:
            raise ValueError('Minutes read must be greater than 0')
        if v > 1440:  # 24 hours = 1440 minutes
            raise ValueError('Minutes read cannot exceed 24 hours (1440 minutes)')
        return v
    
    model_config = {
        "json_schema_extra": {
            "example": {
                "book_id": 1,
                "date": "2024-03-15",
                "minutes_read": 45
            }
        }
    }


class SessionResponse(BaseModel):
    """
    Schema for reading session responses.
    
    Used in GET /sessions endpoint. Represents basic session data with database-generated ID.
    """
    id: int = Field(..., description="Unique identifier of the session")
    book_id: int = Field(..., description="ID of the book being read")
    date: DateType = Field(..., description="Date of the reading session")
    minutes_read: int = Field(..., description="Number of minutes read in this session")
    
    model_config = {
        "from_attributes": True,
        "json_schema_extra": {
            "example": {
                "id": 1,
                "book_id": 1,
                "date": "2024-03-15",
                "minutes_read": 45
            }
        }
    }


class SessionWithBookResponse(BaseModel):
    """
    Schema for reading session responses with book information.
    
    Used when returning session data along with related book details.
    Useful for detailed views and reports that need both session and book info.
    """
    id: int = Field(..., description="Unique identifier of the session")
    book_id: int = Field(..., description="ID of the book being read")
    date: DateType = Field(..., description="Date of the reading session")
    minutes_read: int = Field(..., description="Number of minutes read in this session")
    book_title: str = Field(..., description="Title of the book")
    book_author: str = Field(..., description="Author of the book")
    
    model_config = {
        "from_attributes": True,
        "json_schema_extra": {
            "example": {
                "id": 1,
                "book_id": 1,
                "date": "2024-03-15",
                "minutes_read": 45,
                "book_title": "The Pragmatic Programmer",
                "book_author": "Andrew Hunt"
            }
        }
    }
